Add Morocco regions
elastic/ems-file-service pull request #257
Opened 2022-11-04 14:22 UTC by nelmalki

2022-11-04 14:22 UTC, kibanamachine commented
Since this is a community submitted pull request, a Jenkins build has not been kicked off automatically. Can an Elastic organization member please verify the contents of this patch and then kick off a build manually?

2022-11-04 14:56 UTC, jsanz reviewed
Hi @nelmalki, thanks for your contribution and for signing the CLA.

Your PR looks really well. I have though a couple of comments:

* Your data definition gathers in the same dataset both provinces and regions of Morocco. That's not ideal since you have then overlapping polygons and we prefer to have different datasets for the different hierarchy administrative levels.   Take a look at how Belgium [regions](https://github.com/elastic/ems-file-service/blob/04978e10bb8877972f7d692a9e29e2da3be109c4/sources/be/regions.hjson#L57-L91) and [provinces](https://github.com/elastic/ems-file-service/blob/04978e10bb8877972f7d692a9e29e2da3be109c4/sources/be/provinces.hjson#L57-L91) are defined. Other examples of this practice are Spain, Italy, South Korea, or the United States of America.
* Also, we accept new datasets because they have the freedom to also get labels in countries official languages. I can imagine for Morocco at least adding the Arabic (`ar`) language along with the English one. Maybe also Moroccan Arabic (`ary`)? 

What do you think?

2022-11-04 15:09 UTC, nelmalki commented
> Hi @nelmalki, thanks for your contribution and for signing the CLA.
> 
> Your PR looks really well. I have though a couple of comments:
> 
> * Your data definition gathers in the same dataset both provinces and regions of Morocco. That's not ideal since you have then overlapping polygons and we prefer to have different datasets for the different hierarchy administrative levels.   Take a look at how Belgium [regions](https://github.com/elastic/ems-file-service/blob/04978e10bb8877972f7d692a9e29e2da3be109c4/sources/be/regions.hjson#L57-L91) and [provinces](https://github.com/elastic/ems-file-service/blob/04978e10bb8877972f7d692a9e29e2da3be109c4/sources/be/provinces.hjson#L57-L91) are defined. Other examples of this practice are Spain, Italy, South Korea, or the United States of America.
> * Also, we accept new datasets because they have the freedom to also get labels in countries official languages. I can imagine for Morocco at least adding the Arabic (`ar`) language along with the English one. Maybe also Moroccan Arabic (`ary`)?
> 
> What do you think?

Thanks for your feedkbacks, adaptations in progress !

2022-11-08 14:29 UTC, jsanz commented
@nelmalki thanks for the update. I understand you are only interested then in Morocco regions and not provinces.

I'll review this this week.

2022-11-09 07:55 UTC, nelmalki commented
> @nelmalki thanks for the update. I understand you are only interested then in Morocco regions and not provinces.
> 
> I'll review this this week.

Thanks @jsanz, I encountred multiple missing data at provinces level (not due to missing P150 property). I pushed this update while trying to stabilize the provinces layer

2022-11-09 12:05 UTC, jsanz requested changes
Just a change so this dataset is also available for <8 clients but other than that, this looks good to me. Please fix that and we are good to go.

2022-11-09 12:05 UTC, jsanz commented on sources/ma/regions_v82.hjson
> +      ar: جهات المغرب
I see you tweaked these labels, thanks!

2022-11-10 07:48 UTC, nelmalki commented on sources/ma/regions_v82.hjson
> +    versions: '>=8.2',
all good to go !

2022-11-10 09:46 UTC, jsanz commented
@kibanamachine test this

2022-11-10 09:50 UTC, kibanamachine commented
## :green_heart: Build Succeeded
* [continuous-integration/kibana-ci/pull-request](https://kibana-ci.elastic.co/job/elastic+ems-file-service+pull-request/172/)

2022-11-10 09:51 UTC, jsanz approved these changes
Looks good to me, thanks @nelmalki for your contribution :heart:

2022-11-10 09:51 UTC, merged

2022-11-16 14:18 UTC, jsanz commented
@nelmalki after the small fix at #259 I've deployed the last changes and are available for all Kibana users

https://maps.elastic.co/#file/morocco_regions

![image](https://user-images.githubusercontent.com/188264/202204525-6f144aaf-18c5-4853-92c9-7475d9e3ae2a.png)


Thanks again for your contribution